trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
      jdkFile: ''
      jdkVersionOption: '1.8+'