trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:  
  - task: NodeTool@0
    inputs:
      versionSpec: '16.20.2'
    displayName: 'Install Node.js'